### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by azamet90** [Bowlingtoolkit/Discord-Bots-Hack-Code#12]
how to use and what need to use?

**Comment by Bowlingtoolkit** [comment]
download the script and then be sure you installed nodejs already
then open the script and 
Put your data here
server id etc ,

http://prntscr.com/pumv7r

**Comment by CodingDotExe** [comment]
@azamet90 
- Download [nodejs](https://nodejs.org/en/) and configure it,
- Download [npm](https://www.npmjs.com/) and configure it,
- Download [the repository](https://github.com/Bowlingtoolkit/Discord-Bots-Hack-Code/) and extract it in your desktop,
- Open a new terminal and go to the repository path,
- Type:
```sh
# Will install all dependencies and finnaly
npm install
```
- Open v3.js and modify lines like @Bowlingtoolkit told it before,
- Type in the terminal:
```sh
# Will starts the bot
node v3.js
```

And, that's it 🙂

**Comment by Wessyboy136** [comment]
Yes
