### ISSUE TITLE
Error [TOKEN_INVALID]  "at WebSocketManager.connect" and " at Client.login"

### ISSUE THREAD

**Issue by KK964** [Bowlingtoolkit/Discord-Bots-Hack-Code#17]
error that I got in cmd

D:\mudamaid\Discord-Bots-Hack-Code-master\Discord-Bots-Hack-Code-master>node v3.js

(node:14168) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (D:\mudamaid\Discord-Bots-Hack-Code-master\Discord-Bots-Hack-Code-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:135:26)
    at Client.login (D:\mudamaid\Discord-Bots-Hack-Code-master\Discord-Bots-Hack-Code-master\node_modules\discord.js\src\client\Client.js:220:21)
(node:14168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CodingDotExe** [comment]
If the used token is an account token, it won't work because the newest discord.js lib has removed the possibility to create selfbots. If you want to do it, you have to remove this version and make sure to install the 11.5.1:

```sh
npm i discord.js@11.5.1
```
