### ISSUE TITLE
Very real hack totally hacking

### ISSUE THREAD

**Issue by Shell1010** [Bowlingtoolkit/Discord-Bots-Hack-Code#37]

**Comment by BannaFF** [comment]
Can u give me some hacks

**Comment by Shell1010** [comment]
Ok add me I will give hacks Shell#8627

**Comment by tanjiro1126** [comment]
hi, @Shell1010 im tanjiro kamado in discord i added u as a friend pls teach me how to use this hack, idk how to use it

**Comment by REVENGE977** [comment]
obviously
