### ISSUE TITLE
Loops exist

### ISSUE THREAD

**Issue by Merlintor** [Bowlingtoolkit/Discord-Bots-Hack-Code#8]
https://www.w3schools.com/js/js_loop_for.asp

https://github.com/Bowlingtoolkit/Discord-Bots-Hack-Code/blob/master/here.js#L118-L437

**Comment by CodingDotExe** [comment]
@Merlintor setInterval() can also make a loop, it's identical as while, but with a sleep integrated, so to do some tasks, it could be better.
** setInterval() is also a loop**
