### ISSUE TITLE
shitcode

### ISSUE THREAD

**Issue by Newtox** [Bowlingtoolkit/Discord-Bots-Hack-Code#9]
Hey, I just wanted to tell you, that this code is just cringe and will never work, lol

**Comment by CodingDotExe** [comment]
@Bowlingtoolkit Talking about the perms, checkout your pull requests and forks. I proposed a new version of your script with bug fixed and perms verif :+1:

**Comment by CodingDotExe** [comment]
@Newtox Try my fork, i rewrote his code, it should be work better
